### ISSUE TITLE
Подзадача №1: Распределение обязанностей по должностям

### ISSUE THREAD

**Issue by z-lis** [stankin/oop-stat#2]
Владелец проекта (РП) должен распределить роли и задачи всем участникам проекта

**Comment by mihlo000** [comment]
Утвержденное  распределение по ролям:
РП - Лисица З.
СП - Маслихин В.
НИ - Ружейников М.
ВН - Соловьева Л.
БА - Мавлетдинов Р.
АД - Ружейников М.
КО - Маслихин В.
ПП - Роменкова М.
