### ISSUE TITLE
Подзадача №3: Разработка функциональной модели

### ISSUE THREAD

**Issue by z-lis** [stankin/oop-stat#4]
Архитектор (НИ) проектирует функциональную модель приложения

**Comment by mihlo000** [comment]
Пользователь должен иметь возможность дополнять загруженную модель IDEF0 (JSON), необходимыми данными для ABC/XYZ анализа. Веб-приложение должно предоставлять эту возможность в полном объеме!

**Comment by z-lis** [comment]
Функциональная модель утверждена
